"""create pasien tables

Revision ID: 773019bea03d
Revises: 
Create Date: 2021-08-15 10:41:57.936083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773019bea03d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pasiens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(50), nullable=True),
    sa.Column('gender', sa.String(10), nullable=True),
    sa.Column('no_telp', sa.String(17), nullable=True),
    sa.Column('birthday', sa.DATE(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pasiens_id'), 'pasiens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pasiens_id'), table_name='pasiens')
    op.drop_table('pasiens')
    # ### end Alembic commands ###
